Conditional upgrade of future to v0.18.3 and tabulate to v0.9.0 iff python version is > v3.10. This fixes the error 'ImportError: cannot import name Iterable from collections in Python' on Python 3.10 and higher.